# Generated by Django 5.0.14 on 2025-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(verbose_name='Ссылка на видео (YouTube или Rutube)'),
        ),
    ]
