# Generated by Django 5.0.14 on 2025-12-16 21:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_overview_alter_video_url_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Progress',
                'verbose_name_plural': 'Student Progress Records',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['user', 'course'], name='courses_stu_user_id_6fd6c0_idx'), models.Index(fields=['last_accessed'], name='courses_stu_last_ac_0bb1a4_idx'), models.Index(fields=['completed'], name='courses_stu_complet_9bae4a_idx')],
                'unique_together': {('user', 'course', 'module')},
            },
        ),
    ]
